# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/yqdb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/yqdb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/yqdb/CMakeFiles /workspace/yqdb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/yqdb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yqdb

# Build rule for target.
yqdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yqdb
.PHONY : yqdb

# fast build rule for target.
yqdb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/build
.PHONY : yqdb/fast

#=============================================================================
# Target rules for targets named yq_test_basic

# Build rule for target.
yq_test_basic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yq_test_basic
.PHONY : yq_test_basic

# fast build rule for target.
yq_test_basic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_basic.dir/build.make CMakeFiles/yq_test_basic.dir/build
.PHONY : yq_test_basic/fast

#=============================================================================
# Target rules for targets named yq_test_integration

# Build rule for target.
yq_test_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yq_test_integration
.PHONY : yq_test_integration

# fast build rule for target.
yq_test_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_integration.dir/build.make CMakeFiles/yq_test_integration.dir/build
.PHONY : yq_test_integration/fast

src/yq.o: src/yq.c.o
.PHONY : src/yq.o

# target to build an object file
src/yq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq.c.o
.PHONY : src/yq.c.o

src/yq.i: src/yq.c.i
.PHONY : src/yq.i

# target to preprocess a source file
src/yq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq.c.i
.PHONY : src/yq.c.i

src/yq.s: src/yq.c.s
.PHONY : src/yq.s

# target to generate assembly for a file
src/yq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq.c.s
.PHONY : src/yq.c.s

src/yq_backup.o: src/yq_backup.c.o
.PHONY : src/yq_backup.o

# target to build an object file
src/yq_backup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_backup.c.o
.PHONY : src/yq_backup.c.o

src/yq_backup.i: src/yq_backup.c.i
.PHONY : src/yq_backup.i

# target to preprocess a source file
src/yq_backup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_backup.c.i
.PHONY : src/yq_backup.c.i

src/yq_backup.s: src/yq_backup.c.s
.PHONY : src/yq_backup.s

# target to generate assembly for a file
src/yq_backup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_backup.c.s
.PHONY : src/yq_backup.c.s

src/yq_batch.o: src/yq_batch.c.o
.PHONY : src/yq_batch.o

# target to build an object file
src/yq_batch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_batch.c.o
.PHONY : src/yq_batch.c.o

src/yq_batch.i: src/yq_batch.c.i
.PHONY : src/yq_batch.i

# target to preprocess a source file
src/yq_batch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_batch.c.i
.PHONY : src/yq_batch.c.i

src/yq_batch.s: src/yq_batch.c.s
.PHONY : src/yq_batch.s

# target to generate assembly for a file
src/yq_batch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_batch.c.s
.PHONY : src/yq_batch.c.s

src/yq_btree.o: src/yq_btree.c.o
.PHONY : src/yq_btree.o

# target to build an object file
src/yq_btree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_btree.c.o
.PHONY : src/yq_btree.c.o

src/yq_btree.i: src/yq_btree.c.i
.PHONY : src/yq_btree.i

# target to preprocess a source file
src/yq_btree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_btree.c.i
.PHONY : src/yq_btree.c.i

src/yq_btree.s: src/yq_btree.c.s
.PHONY : src/yq_btree.s

# target to generate assembly for a file
src/yq_btree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_btree.c.s
.PHONY : src/yq_btree.c.s

src/yq_cache.o: src/yq_cache.c.o
.PHONY : src/yq_cache.o

# target to build an object file
src/yq_cache.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_cache.c.o
.PHONY : src/yq_cache.c.o

src/yq_cache.i: src/yq_cache.c.i
.PHONY : src/yq_cache.i

# target to preprocess a source file
src/yq_cache.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_cache.c.i
.PHONY : src/yq_cache.c.i

src/yq_cache.s: src/yq_cache.c.s
.PHONY : src/yq_cache.s

# target to generate assembly for a file
src/yq_cache.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_cache.c.s
.PHONY : src/yq_cache.c.s

src/yq_cluster.o: src/yq_cluster.c.o
.PHONY : src/yq_cluster.o

# target to build an object file
src/yq_cluster.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_cluster.c.o
.PHONY : src/yq_cluster.c.o

src/yq_cluster.i: src/yq_cluster.c.i
.PHONY : src/yq_cluster.i

# target to preprocess a source file
src/yq_cluster.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_cluster.c.i
.PHONY : src/yq_cluster.c.i

src/yq_cluster.s: src/yq_cluster.c.s
.PHONY : src/yq_cluster.s

# target to generate assembly for a file
src/yq_cluster.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_cluster.c.s
.PHONY : src/yq_cluster.c.s

src/yq_compress.o: src/yq_compress.c.o
.PHONY : src/yq_compress.o

# target to build an object file
src/yq_compress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_compress.c.o
.PHONY : src/yq_compress.c.o

src/yq_compress.i: src/yq_compress.c.i
.PHONY : src/yq_compress.i

# target to preprocess a source file
src/yq_compress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_compress.c.i
.PHONY : src/yq_compress.c.i

src/yq_compress.s: src/yq_compress.c.s
.PHONY : src/yq_compress.s

# target to generate assembly for a file
src/yq_compress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_compress.c.s
.PHONY : src/yq_compress.c.s

src/yq_crypto.o: src/yq_crypto.c.o
.PHONY : src/yq_crypto.o

# target to build an object file
src/yq_crypto.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_crypto.c.o
.PHONY : src/yq_crypto.c.o

src/yq_crypto.i: src/yq_crypto.c.i
.PHONY : src/yq_crypto.i

# target to preprocess a source file
src/yq_crypto.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_crypto.c.i
.PHONY : src/yq_crypto.c.i

src/yq_crypto.s: src/yq_crypto.c.s
.PHONY : src/yq_crypto.s

# target to generate assembly for a file
src/yq_crypto.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_crypto.c.s
.PHONY : src/yq_crypto.c.s

src/yq_enc.o: src/yq_enc.c.o
.PHONY : src/yq_enc.o

# target to build an object file
src/yq_enc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_enc.c.o
.PHONY : src/yq_enc.c.o

src/yq_enc.i: src/yq_enc.c.i
.PHONY : src/yq_enc.i

# target to preprocess a source file
src/yq_enc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_enc.c.i
.PHONY : src/yq_enc.c.i

src/yq_enc.s: src/yq_enc.c.s
.PHONY : src/yq_enc.s

# target to generate assembly for a file
src/yq_enc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_enc.c.s
.PHONY : src/yq_enc.c.s

src/yq_index.o: src/yq_index.c.o
.PHONY : src/yq_index.o

# target to build an object file
src/yq_index.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_index.c.o
.PHONY : src/yq_index.c.o

src/yq_index.i: src/yq_index.c.i
.PHONY : src/yq_index.i

# target to preprocess a source file
src/yq_index.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_index.c.i
.PHONY : src/yq_index.c.i

src/yq_index.s: src/yq_index.c.s
.PHONY : src/yq_index.s

# target to generate assembly for a file
src/yq_index.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_index.c.s
.PHONY : src/yq_index.c.s

src/yq_json.o: src/yq_json.c.o
.PHONY : src/yq_json.o

# target to build an object file
src/yq_json.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_json.c.o
.PHONY : src/yq_json.c.o

src/yq_json.i: src/yq_json.c.i
.PHONY : src/yq_json.i

# target to preprocess a source file
src/yq_json.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_json.c.i
.PHONY : src/yq_json.c.i

src/yq_json.s: src/yq_json.c.s
.PHONY : src/yq_json.s

# target to generate assembly for a file
src/yq_json.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_json.c.s
.PHONY : src/yq_json.c.s

src/yq_memblk.o: src/yq_memblk.c.o
.PHONY : src/yq_memblk.o

# target to build an object file
src/yq_memblk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_memblk.c.o
.PHONY : src/yq_memblk.c.o

src/yq_memblk.i: src/yq_memblk.c.i
.PHONY : src/yq_memblk.i

# target to preprocess a source file
src/yq_memblk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_memblk.c.i
.PHONY : src/yq_memblk.c.i

src/yq_memblk.s: src/yq_memblk.c.s
.PHONY : src/yq_memblk.s

# target to generate assembly for a file
src/yq_memblk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_memblk.c.s
.PHONY : src/yq_memblk.c.s

src/yq_memtable.o: src/yq_memtable.c.o
.PHONY : src/yq_memtable.o

# target to build an object file
src/yq_memtable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_memtable.c.o
.PHONY : src/yq_memtable.c.o

src/yq_memtable.i: src/yq_memtable.c.i
.PHONY : src/yq_memtable.i

# target to preprocess a source file
src/yq_memtable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_memtable.c.i
.PHONY : src/yq_memtable.c.i

src/yq_memtable.s: src/yq_memtable.c.s
.PHONY : src/yq_memtable.s

# target to generate assembly for a file
src/yq_memtable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_memtable.c.s
.PHONY : src/yq_memtable.c.s

src/yq_mvcc.o: src/yq_mvcc.c.o
.PHONY : src/yq_mvcc.o

# target to build an object file
src/yq_mvcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_mvcc.c.o
.PHONY : src/yq_mvcc.c.o

src/yq_mvcc.i: src/yq_mvcc.c.i
.PHONY : src/yq_mvcc.i

# target to preprocess a source file
src/yq_mvcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_mvcc.c.i
.PHONY : src/yq_mvcc.c.i

src/yq_mvcc.s: src/yq_mvcc.c.s
.PHONY : src/yq_mvcc.s

# target to generate assembly for a file
src/yq_mvcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_mvcc.c.s
.PHONY : src/yq_mvcc.c.s

src/yq_pubsub.o: src/yq_pubsub.c.o
.PHONY : src/yq_pubsub.o

# target to build an object file
src/yq_pubsub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_pubsub.c.o
.PHONY : src/yq_pubsub.c.o

src/yq_pubsub.i: src/yq_pubsub.c.i
.PHONY : src/yq_pubsub.i

# target to preprocess a source file
src/yq_pubsub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_pubsub.c.i
.PHONY : src/yq_pubsub.c.i

src/yq_pubsub.s: src/yq_pubsub.c.s
.PHONY : src/yq_pubsub.s

# target to generate assembly for a file
src/yq_pubsub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_pubsub.c.s
.PHONY : src/yq_pubsub.c.s

src/yq_recover.o: src/yq_recover.c.o
.PHONY : src/yq_recover.o

# target to build an object file
src/yq_recover.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_recover.c.o
.PHONY : src/yq_recover.c.o

src/yq_recover.i: src/yq_recover.c.i
.PHONY : src/yq_recover.i

# target to preprocess a source file
src/yq_recover.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_recover.c.i
.PHONY : src/yq_recover.c.i

src/yq_recover.s: src/yq_recover.c.s
.PHONY : src/yq_recover.s

# target to generate assembly for a file
src/yq_recover.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_recover.c.s
.PHONY : src/yq_recover.c.s

src/yq_slice.o: src/yq_slice.c.o
.PHONY : src/yq_slice.o

# target to build an object file
src/yq_slice.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_slice.c.o
.PHONY : src/yq_slice.c.o

src/yq_slice.i: src/yq_slice.c.i
.PHONY : src/yq_slice.i

# target to preprocess a source file
src/yq_slice.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_slice.c.i
.PHONY : src/yq_slice.c.i

src/yq_slice.s: src/yq_slice.c.s
.PHONY : src/yq_slice.s

# target to generate assembly for a file
src/yq_slice.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_slice.c.s
.PHONY : src/yq_slice.c.s

src/yq_test_basic.o: src/yq_test_basic.c.o
.PHONY : src/yq_test_basic.o

# target to build an object file
src/yq_test_basic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_basic.dir/build.make CMakeFiles/yq_test_basic.dir/src/yq_test_basic.c.o
.PHONY : src/yq_test_basic.c.o

src/yq_test_basic.i: src/yq_test_basic.c.i
.PHONY : src/yq_test_basic.i

# target to preprocess a source file
src/yq_test_basic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_basic.dir/build.make CMakeFiles/yq_test_basic.dir/src/yq_test_basic.c.i
.PHONY : src/yq_test_basic.c.i

src/yq_test_basic.s: src/yq_test_basic.c.s
.PHONY : src/yq_test_basic.s

# target to generate assembly for a file
src/yq_test_basic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_basic.dir/build.make CMakeFiles/yq_test_basic.dir/src/yq_test_basic.c.s
.PHONY : src/yq_test_basic.c.s

src/yq_test_integration.o: src/yq_test_integration.c.o
.PHONY : src/yq_test_integration.o

# target to build an object file
src/yq_test_integration.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_integration.dir/build.make CMakeFiles/yq_test_integration.dir/src/yq_test_integration.c.o
.PHONY : src/yq_test_integration.c.o

src/yq_test_integration.i: src/yq_test_integration.c.i
.PHONY : src/yq_test_integration.i

# target to preprocess a source file
src/yq_test_integration.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_integration.dir/build.make CMakeFiles/yq_test_integration.dir/src/yq_test_integration.c.i
.PHONY : src/yq_test_integration.c.i

src/yq_test_integration.s: src/yq_test_integration.c.s
.PHONY : src/yq_test_integration.s

# target to generate assembly for a file
src/yq_test_integration.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yq_test_integration.dir/build.make CMakeFiles/yq_test_integration.dir/src/yq_test_integration.c.s
.PHONY : src/yq_test_integration.c.s

src/yq_ttl.o: src/yq_ttl.c.o
.PHONY : src/yq_ttl.o

# target to build an object file
src/yq_ttl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_ttl.c.o
.PHONY : src/yq_ttl.c.o

src/yq_ttl.i: src/yq_ttl.c.i
.PHONY : src/yq_ttl.i

# target to preprocess a source file
src/yq_ttl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_ttl.c.i
.PHONY : src/yq_ttl.c.i

src/yq_ttl.s: src/yq_ttl.c.s
.PHONY : src/yq_ttl.s

# target to generate assembly for a file
src/yq_ttl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_ttl.c.s
.PHONY : src/yq_ttl.c.s

src/yq_vfs.o: src/yq_vfs.c.o
.PHONY : src/yq_vfs.o

# target to build an object file
src/yq_vfs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_vfs.c.o
.PHONY : src/yq_vfs.c.o

src/yq_vfs.i: src/yq_vfs.c.i
.PHONY : src/yq_vfs.i

# target to preprocess a source file
src/yq_vfs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_vfs.c.i
.PHONY : src/yq_vfs.c.i

src/yq_vfs.s: src/yq_vfs.c.s
.PHONY : src/yq_vfs.s

# target to generate assembly for a file
src/yq_vfs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_vfs.c.s
.PHONY : src/yq_vfs.c.s

src/yq_wal.o: src/yq_wal.c.o
.PHONY : src/yq_wal.o

# target to build an object file
src/yq_wal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_wal.c.o
.PHONY : src/yq_wal.c.o

src/yq_wal.i: src/yq_wal.c.i
.PHONY : src/yq_wal.i

# target to preprocess a source file
src/yq_wal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_wal.c.i
.PHONY : src/yq_wal.c.i

src/yq_wal.s: src/yq_wal.c.s
.PHONY : src/yq_wal.s

# target to generate assembly for a file
src/yq_wal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_wal.c.s
.PHONY : src/yq_wal.c.s

src/yq_web.o: src/yq_web.c.o
.PHONY : src/yq_web.o

# target to build an object file
src/yq_web.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_web.c.o
.PHONY : src/yq_web.c.o

src/yq_web.i: src/yq_web.c.i
.PHONY : src/yq_web.i

# target to preprocess a source file
src/yq_web.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_web.c.i
.PHONY : src/yq_web.c.i

src/yq_web.s: src/yq_web.c.s
.PHONY : src/yq_web.s

# target to generate assembly for a file
src/yq_web.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_web.c.s
.PHONY : src/yq_web.c.s

src/yq_web_missing_functions.o: src/yq_web_missing_functions.c.o
.PHONY : src/yq_web_missing_functions.o

# target to build an object file
src/yq_web_missing_functions.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_web_missing_functions.c.o
.PHONY : src/yq_web_missing_functions.c.o

src/yq_web_missing_functions.i: src/yq_web_missing_functions.c.i
.PHONY : src/yq_web_missing_functions.i

# target to preprocess a source file
src/yq_web_missing_functions.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_web_missing_functions.c.i
.PHONY : src/yq_web_missing_functions.c.i

src/yq_web_missing_functions.s: src/yq_web_missing_functions.c.s
.PHONY : src/yq_web_missing_functions.s

# target to generate assembly for a file
src/yq_web_missing_functions.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yqdb.dir/build.make CMakeFiles/yqdb.dir/src/yq_web_missing_functions.c.s
.PHONY : src/yq_web_missing_functions.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... yq_test_basic"
	@echo "... yq_test_integration"
	@echo "... yqdb"
	@echo "... src/yq.o"
	@echo "... src/yq.i"
	@echo "... src/yq.s"
	@echo "... src/yq_backup.o"
	@echo "... src/yq_backup.i"
	@echo "... src/yq_backup.s"
	@echo "... src/yq_batch.o"
	@echo "... src/yq_batch.i"
	@echo "... src/yq_batch.s"
	@echo "... src/yq_btree.o"
	@echo "... src/yq_btree.i"
	@echo "... src/yq_btree.s"
	@echo "... src/yq_cache.o"
	@echo "... src/yq_cache.i"
	@echo "... src/yq_cache.s"
	@echo "... src/yq_cluster.o"
	@echo "... src/yq_cluster.i"
	@echo "... src/yq_cluster.s"
	@echo "... src/yq_compress.o"
	@echo "... src/yq_compress.i"
	@echo "... src/yq_compress.s"
	@echo "... src/yq_crypto.o"
	@echo "... src/yq_crypto.i"
	@echo "... src/yq_crypto.s"
	@echo "... src/yq_enc.o"
	@echo "... src/yq_enc.i"
	@echo "... src/yq_enc.s"
	@echo "... src/yq_index.o"
	@echo "... src/yq_index.i"
	@echo "... src/yq_index.s"
	@echo "... src/yq_json.o"
	@echo "... src/yq_json.i"
	@echo "... src/yq_json.s"
	@echo "... src/yq_memblk.o"
	@echo "... src/yq_memblk.i"
	@echo "... src/yq_memblk.s"
	@echo "... src/yq_memtable.o"
	@echo "... src/yq_memtable.i"
	@echo "... src/yq_memtable.s"
	@echo "... src/yq_mvcc.o"
	@echo "... src/yq_mvcc.i"
	@echo "... src/yq_mvcc.s"
	@echo "... src/yq_pubsub.o"
	@echo "... src/yq_pubsub.i"
	@echo "... src/yq_pubsub.s"
	@echo "... src/yq_recover.o"
	@echo "... src/yq_recover.i"
	@echo "... src/yq_recover.s"
	@echo "... src/yq_slice.o"
	@echo "... src/yq_slice.i"
	@echo "... src/yq_slice.s"
	@echo "... src/yq_test_basic.o"
	@echo "... src/yq_test_basic.i"
	@echo "... src/yq_test_basic.s"
	@echo "... src/yq_test_integration.o"
	@echo "... src/yq_test_integration.i"
	@echo "... src/yq_test_integration.s"
	@echo "... src/yq_ttl.o"
	@echo "... src/yq_ttl.i"
	@echo "... src/yq_ttl.s"
	@echo "... src/yq_vfs.o"
	@echo "... src/yq_vfs.i"
	@echo "... src/yq_vfs.s"
	@echo "... src/yq_wal.o"
	@echo "... src/yq_wal.i"
	@echo "... src/yq_wal.s"
	@echo "... src/yq_web.o"
	@echo "... src/yq_web.i"
	@echo "... src/yq_web.s"
	@echo "... src/yq_web_missing_functions.o"
	@echo "... src/yq_web_missing_functions.i"
	@echo "... src/yq_web_missing_functions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

